set(_CATKIN_CURRENT_PACKAGE "geotag")
set(geotag_VERSION "0.0.0")
set(geotag_MAINTAINER "root <root@todo.todo>")
set(geotag_PACKAGE_FORMAT "2")
set(geotag_BUILD_DEPENDS "mavros_msgs" "rospy" "sensor_msgs" "std_msgs")
set(geotag_BUILD_EXPORT_DEPENDS "mavros_msgs" "rospy" "sensor_msgs" "std_msgs")
set(geotag_BUILDTOOL_DEPENDS "catkin")
set(geotag_BUILDTOOL_EXPORT_DEPENDS )
set(geotag_EXEC_DEPENDS "mavros_msgs" "rospy" "sensor_msgs" "std_msgs")
set(geotag_RUN_DEPENDS "mavros_msgs" "rospy" "sensor_msgs" "std_msgs")
set(geotag_TEST_DEPENDS )
set(geotag_DOC_DEPENDS )
set(geotag_URL_WEBSITE "")
set(geotag_URL_BUGTRACKER "")
set(geotag_URL_REPOSITORY "")
set(geotag_DEPRECATED "")